frase = '    Claudinei Macedo Pires de Carvalho da Sila    '
print(frase.upper())
print(frase.lower())
print(len(frase.strip()))
dividido = frase.split()
print(dividido[0])
print(dividido[1])
print(dividido[2])
print(dividido[3])
print(dividido[4])
print(dividido[5])
print(dividido[6])